import Head from "next/head";
import React from "react";
import Header from "./components/Header";
import dynamic from "next/dynamic";
import SidePanel from "./components/SidePanel";

export default function Home() {
  // No Server Side Rendering
  const MapWithNoSSR = dynamic(() => import("./components/Map"), {
    ssr: false,
  });
  return (
    <div>
      <Head>
        <title>Travel Diary</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <SidePanel />
      <div className="ml-[42rem] pt-20 flex flex-col">
        <div id="map">
          <MapWithNoSSR />
        </div>
      </div>
    </div>
  );
}
